### ISSUE TITLE
https://github.com/JORGE-SAPIS/SHARKS-_IN_DISGUISE

### ISSUE THREAD

**Issue by JORGE-SAPIS** [Ironhack-Data-Madrid-Mayo-2022/W2-Sharks-Clean-Project#3]

**Comment by Gobuub** [comment]
Como ya te comenté se te pasó poner el enlace, el tema la limpieza pues poco a poco lo irás pillando, pero vamos por buen camino, y me gusta mucho tu actitud, sigue así Jorge.
