### ISSUE TITLE
https://github.com/luciaahab/jaws_attack.git

### ISSUE THREAD

**Issue by luciaahab** [Ironhack-Data-Madrid-Mayo-2022/W2-Sharks-Clean-Project#4]

**Comment by Gobuub** [comment]
El análisis perfecto, por poner un pero porque siempre me gusta ver el margen de mejora, la limpieza podría haber sido más exhaustiva, pero vamos que es por poner un pero :P.

**Comment by luciaahab** [comment]
ya, es que no daba más. ¿cómo lo habrías hecho tú?
