### ISSUE TITLE
https://github.com/OrianAmpuero/Project-Shark.git

### ISSUE THREAD

**Issue by OrianAmpuero** [Ironhack-Data-Madrid-Mayo-2022/W2-Sharks-Clean-Project#5]

**Comment by Gobuub** [comment]
Buen trabajo Oriana, pero tuve que buscar tu repo en tu perfil de git porque no me pasaste el enlace en los comentarios como habiamos pedido, este al ser el primero somos flexibles, pero el próximo saco la vara :P.
