### ISSUE TITLE
[Jennifer Atance] W2-Sharks-Clean-Project

### ISSUE THREAD

**Issue by jenatance** [Ironhack-Data-Madrid-Mayo-2022/W2-Sharks-Clean-Project#6]
https://github.com/jenatance/Cleaning_Sharks

**Comment by Gobuub** [comment]
Buen trabajo Jenni, mucho curro te has pegado con los replaces y los index, como ya hablamos ayer, había otra manera, pero nadie nace enseñado ;). Sigue así, que no vas ha tener problema de curro.
