### ISSUE TITLE
[Irene Aguerri] - Sharks project

### ISSUE THREAD

**Issue by iaguerri** [Ironhack-Data-Madrid-Mayo-2022/W2-Sharks-Clean-Project#7]
It could be better ;) 
https://github.com/iaguerri/Global-Sharks

**Comment by Gobuub** [comment]
Muy buen trabajo Irene, los gráficos muy bien elegidos, e ilustran perfectamente la evolución y el progreso del proyecto. Poco mas puedo añadir.
